/* Generated By:JavaCC: Do not edit this line. EG1.java */
package kvv.evlang;
import java.io.*;
import java.util.*;
import kvv.evlang.impl.*;
import kvv.evlang.impl.Locals.Local;
import kvv.controllers.register.*;

public abstract class EG1 extends EG implements EG1Constants {
  public EG1(String fileName) throws FileNotFoundException
  {
        //this(new InputStreamReader(new FileInputStream(fileName), "Windows-1251"));
//    this (new FileReader(fileName));
    this (new JavaCCReader(fileName));
  }

  public void throwExc(String msg) throws ParseException
  {
        throw new ParseException(token, msg);
  }

  public void parse(String controllerType) throws ParseException, IOException
  {
    init(controllerType);
    file();
    buildInit();
    check();
    genCode();
    //checkStack();
  }

  final public void file() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
      break;
    case REG:
    case EEREG:
    case CONST:
    case CHECKBOX:
    case TEXT:
    case INT:
    case VOID:
    case STRUCT:
    case ID:
      line();
      file();
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void line() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONST:
      constant();
      break;
    case REG:
    case EEREG:
      register();
      break;
    case INT:
    case VOID:
    case ID:
      varOrProc();
      break;
    case CHECKBOX:
    case TEXT:
      uiDecl();
      break;
    case STRUCT:
      struct();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void varOrProc() throws ParseException {
  Type type;
  String name;
  String className = null;
    type = type();
    if (jj_2_1(2)) {
      className = id();
      jj_consume_token(49);
    } else {
      ;
    }
    name = id();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 55:
      proc(type, name, className == null ? null : new Type(className));
      break;
    case 51:
    case 58:
      var(type, name);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void struct() throws ParseException {
  String name;
  String name1 = null;
  String fieldName;
  Type fieldType;
    jj_consume_token(STRUCT);
    name = id();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 49:
      jj_consume_token(49);
      name1 = id();
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    declareStruct(name);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 50:
      jj_consume_token(50);
      createStruct(name, name1);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case INT:
        case VOID:
        case ID:
          ;
          break;
        default:
          jj_la1[4] = jj_gen;
          break label_1;
        }
        fieldType = type();
        fieldName = id();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 55:
          proc(fieldType, fieldName, new Type(name));
          break;
        case 51:
          jj_consume_token(51);
          fieldType.checkNotVoid(this);
          createField(name, fieldType, fieldName);
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(52);
      closeStruct(name);
      break;
    case 51:
      jj_consume_token(51);
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public Type type() throws ParseException {
  Type type;
  int cnt = 0;
    type = typeBase();
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 53:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      jj_consume_token(53);
      jj_consume_token(54);
      type.checkNotVoid(this);
      cnt++;
    }
    if (cnt == 0) {if (true) return type;}
    else {if (true) return new Type(type, cnt);}
    throw new Error("Missing return statement in function");
  }

  final public Type typeBase() throws ParseException {
  String name = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VOID:
      jj_consume_token(VOID);
    {if (true) return Type.VOID;}
      break;
    case INT:
      jj_consume_token(INT);
    {if (true) return Type.INT;}
      break;
    case ID:
      name = id();
    {if (true) return new Type(name);}
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void proc(Type type, String name, Type thisType) throws ParseException {
  Code bytes = null;
  Locals locals = new Locals();
    if(thisType != null)
        locals.addThis(thisType);
    jj_consume_token(55);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INT:
    case VOID:
    case ID:
      argListDef(locals);
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
    jj_consume_token(56);
        declareFunc(type, thisType, name, locals);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 50:
      bytes = stmtBlock();
      Code.procCode(this, bytes);
      break;
    case 51:
      jj_consume_token(51);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void argListDef(Locals locals) throws ParseException {
    localDef(locals);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 57:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_3;
      }
      jj_consume_token(57);
      localDef(locals);
    }
  }

  final public Local localDef(Locals locals) throws ParseException {
  String name;
  Type type;
    type = type();
    name = id();
      type.checkNotVoid(this);
      {if (true) return locals.add(new NameAndType(name, type));}
    throw new Error("Missing return statement in function");
  }

  final public void constant() throws ParseException {
  String name;
  short value;
    jj_consume_token(CONST);
    name = id();
    jj_consume_token(58);
    value = number();
    jj_consume_token(51);
    checkName(name);
    constants.put(name, value);
  }

  final public void uiDecl() throws ParseException {
  String name;
  Token text;
  RegType type;
    type = uitype();
    name = id();
    text = jj_consume_token(STRING);
    jj_consume_token(51);
    registers.setUI(name, text.image.replace("\u005c"", ""), type);
  }

  final public RegType uitype() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CHECKBOX:
      t = jj_consume_token(CHECKBOX);
    {if (true) return RegType.checkbox;}
      break;
    case TEXT:
      t = jj_consume_token(TEXT);
    {if (true) return RegType.textRW;}
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void var(Type type, String name) throws ParseException {
  Expr e = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 58:
      jj_consume_token(58);
      e = expr();
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(51);
         type.checkNotVoid(this);
         registers.newVar(type, name, e);
  }

  final public void register() throws ParseException {
  String regName;
  String regNum = null;
  short initVal;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case REG:
      jj_consume_token(REG);
      regName = id();
      jj_consume_token(55);
      regNum = id();
      jj_consume_token(56);
      jj_consume_token(51);
    registers.newRegisterAlias(regName, regNum);
      break;
    case EEREG:
      jj_consume_token(EEREG);
      regName = id();
      jj_consume_token(58);
      initVal = number();
      jj_consume_token(51);
    registers.newEERegister(regName, initVal);
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public Code stmtBlock() throws ParseException {
  Code bytes = new Code(this);
  Code temp;
  int localpos = currentFunc.locals.getSize();
    jj_consume_token(50);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
      case PRINT:
      case INT:
      case VOID:
      case RETURN:
      case TRY:
      case THROW:
      case NEW:
      case TRAP:
      case WHILE:
      case ID:
      case 50:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_4;
      }
      temp = stmt();
      bytes.addAll(temp);
    }
    jj_consume_token(52);
    currentFunc.locals.setSize(localpos);
    {if (true) return bytes;}
    throw new Error("Missing return statement in function");
  }

  final public Code stmt() throws ParseException {
  Code res;
    if (jj_2_2(2)) {
      res = assign();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IF:
        res = ifStmt();
        break;
      case WHILE:
        res = whileStmt();
        break;
      case TRY:
        res = tryCatchStmt();
        break;
      case TRAP:
        jj_consume_token(TRAP);
        jj_consume_token(51);
    res = Code.trap(this);
        break;
      case 50:
        res = stmtBlock();
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

  final public Code tryCatchStmt() throws ParseException {
  Code tryStmt;
  Code catchStmt;
  Local local;
    jj_consume_token(TRY);
    tryStmt = stmtBlock();
    jj_consume_token(CATCH);
    jj_consume_token(55);
    local = localDef(currentFunc.locals);
    jj_consume_token(56);
    catchStmt = stmtBlock();
    {if (true) return Code.trycatchstmt(this, tryStmt, catchStmt, local);}
    throw new Error("Missing return statement in function");
  }

  final public Code ifStmt() throws ParseException {
  Expr res;
  Code stmt;
  Code stmt2 = null;
    jj_consume_token(IF);
    jj_consume_token(55);
    res = expr();
    jj_consume_token(56);
    stmt = stmt();
    if (jj_2_3(2)) {
      jj_consume_token(ELSE);
      stmt2 = stmt();
    } else {
      ;
    }
    {if (true) return Code.ifstmt(res, stmt, stmt2);}
    throw new Error("Missing return statement in function");
  }

  final public Code whileStmt() throws ParseException {
  Expr res;
  Code stmt;
    jj_consume_token(WHILE);
    jj_consume_token(55);
    res = expr();
    jj_consume_token(56);
    stmt = stmt();
    {if (true) return Code.whilestmt(res, stmt);}
    throw new Error("Missing return statement in function");
  }

  final public Code assign() throws ParseException {
  Expr res = null;
  LValue lvalue;
  String name;
  List < Expr > argList = new ArrayList < Expr > ();
  Local local;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case PRINT:
      jj_consume_token(PRINT);
      res = expr();
      jj_consume_token(51);
    {if (true) return Code.print(res);}
      break;
    case RETURN:
      jj_consume_token(RETURN);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
      case MINUS:
      case MULDIV:
      case NULL:
      case NEW:
      case ID:
      case NUMBER:
      case 55:
        res = expr();
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
      jj_consume_token(51);
    {if (true) return Code.ret(this, res);}
      break;
    case THROW:
      jj_consume_token(THROW);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
      case MINUS:
      case MULDIV:
      case NULL:
      case NEW:
      case ID:
      case NUMBER:
      case 55:
        res = expr();
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      jj_consume_token(51);
    {if (true) return Code.throw_(this, res);}
      break;
    default:
      jj_la1[20] = jj_gen;
      if (jj_2_4(3)) {
        local = localDef(currentFunc.locals);
        jj_consume_token(58);
        res = expr();
        jj_consume_token(51);
    {if (true) return Code.initLocal(this, local, res);}
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case NEW:
        case ID:
          lvalue = lvalue1();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 58:
            jj_consume_token(58);
            res = expr();
            break;
          default:
            jj_la1[19] = jj_gen;
            ;
          }
          jj_consume_token(51);
    {if (true) return lvalue.assign(res);}
          break;
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public Expr expr() throws ParseException {
  List < Expr > res = new ArrayList < Expr > ();
  Expr temp;
    temp = logAndExpr();
    res.add(temp);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[22] = jj_gen;
        break label_5;
      }
      jj_consume_token(OR);
      temp = logAndExpr();
      res.add(temp);
    }
    {if (true) return Expr.or(this, res);}
    throw new Error("Missing return statement in function");
  }

  final public Expr logAndExpr() throws ParseException {
  List < Expr > res = new ArrayList < Expr > ();
  Expr temp;
    temp = boolExpr();
    res.add(temp);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[23] = jj_gen;
        break label_6;
      }
      jj_consume_token(AND);
      temp = boolExpr();
      res.add(temp);
    }
    {if (true) return Expr.and(this, res);}
    throw new Error("Missing return statement in function");
  }

  final public Expr boolExpr() throws ParseException {
  Expr res;
  Expr temp;
    res = intExpr();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
      case NEQ:
      case LT:
      case LE:
      case GT:
      case GE:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        jj_consume_token(EQ);
        temp = intExpr();
        res = Expr.eq(this, res, temp);
        break;
      case NEQ:
        jj_consume_token(NEQ);
        temp = intExpr();
        res = Expr.neq(this,res, temp);
        break;
      case LT:
        jj_consume_token(LT);
        temp = intExpr();
        res = Expr.lt(this,res, temp);
        break;
      case LE:
        jj_consume_token(LE);
        temp = intExpr();
        res = Expr.le(this,res, temp);
        break;
      case GT:
        jj_consume_token(GT);
        temp = intExpr();
        res = Expr.gt(this,res, temp);
        break;
      case GE:
        jj_consume_token(GE);
        temp = intExpr();
        res = Expr.ge(this,res, temp);
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

  final public Expr intExpr() throws ParseException {
  Expr res;
  Expr temp;
    res = term();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[26] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        temp = term();
        res = Expr.add(this,res, temp);
        break;
      case MINUS:
        jj_consume_token(MINUS);
        temp = term();
        res = Expr.sub(this,res, temp);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

  final public Expr term() throws ParseException {
  Expr res;
  Expr temp;
    res = unary();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
      case DIVIDE:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
        jj_consume_token(MULTIPLY);
        temp = unary();
        res = Expr.mul(this, res, temp);
        break;
      case DIVIDE:
        jj_consume_token(DIVIDE);
        temp = unary();
        res = Expr.div(this, res, temp);
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

  final public Expr unary() throws ParseException {
  Expr res;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOT:
      jj_consume_token(NOT);
      res = element();
    {if (true) return Expr.not(this, res);}
      break;
    case MINUS:
      jj_consume_token(MINUS);
      res = element();
    {if (true) return Expr.negate(this, res);}
      break;
    case MULDIV:
    case NULL:
    case NEW:
    case ID:
    case NUMBER:
    case 55:
      res = element();
    {if (true) return res;}
      break;
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Expr element() throws ParseException {
  Expr res;
  LValue lvalue;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MULDIV:
    case NULL:
    case NUMBER:
    case 55:
      res = simpleElement();
    {if (true) return res;}
      break;
    case NEW:
    case ID:
      lvalue = lvalue1();
    {if (true) return lvalue.getExpr();}
      break;
    default:
      jj_la1[31] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public LValue lvalue1() throws ParseException {
  LValue res;
  Expr expr;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ID:
      res = field(null);
      break;
    case NEW:
      expr = newExpr();
      res = new LValue(this, expr);
      break;
    default:
      jj_la1[32] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 53:
      case 59:
        ;
        break;
      default:
        jj_la1[33] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 59:
        jj_consume_token(59);
        res = field(res);
        break;
      case 53:
        jj_consume_token(53);
        res = index(res);
        jj_consume_token(54);
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

  final public LValue index(LValue left) throws ParseException {
  Expr expr;
    expr = expr();
    {if (true) return new LValue(this, left, expr);}
    throw new Error("Missing return statement in function");
  }

  final public LValue field(LValue left) throws ParseException {
  String name;
  List < Expr > argList = null;
    name = id();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 55:
      jj_consume_token(55);
      argList = new ArrayList < Expr > ();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
      case MINUS:
      case MULDIV:
      case NULL:
      case NEW:
      case ID:
      case NUMBER:
      case 55:
        argList = argList();
        break;
      default:
        jj_la1[35] = jj_gen;
        ;
      }
      jj_consume_token(56);
      break;
    default:
      jj_la1[36] = jj_gen;
      ;
    }
    {if (true) return new LValue(this, left, name, argList);}
    throw new Error("Missing return statement in function");
  }

  final public Expr simpleElement() throws ParseException {
  short n;
  String name;
  List < Expr > argList = null;
  Expr res;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NULL:
      jj_consume_token(NULL);
    {if (true) return Expr.nullExpr(this);}
      break;
    case NUMBER:
      n = number();
    {if (true) return new Expr(this, n);}
      break;
    case MULDIV:
      res = muldiv();
    {if (true) return res;}
      break;
    case 55:
      jj_consume_token(55);
      res = expr();
      jj_consume_token(56);
    {if (true) return res;}
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Expr muldiv() throws ParseException {
  Expr res;
  Expr temp;
  Expr temp1;
    jj_consume_token(MULDIV);
    jj_consume_token(55);
    res = expr();
    jj_consume_token(57);
    temp = expr();
    jj_consume_token(57);
    temp1 = expr();
    jj_consume_token(56);
    {if (true) return Expr.muldiv(this, res, temp, temp1);}
    throw new Error("Missing return statement in function");
  }

  final public Expr newExpr() throws ParseException {
  Type type;
  int arrDepth = 0;
  Expr arrSize = null;
    jj_consume_token(NEW);
    type = typeBase();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 53:
      jj_consume_token(53);
      arrSize = expr();
      jj_consume_token(54);
      arrDepth = 1;
      label_11:
      while (true) {
        if (jj_2_5(2)) {
          ;
        } else {
          break label_11;
        }
        jj_consume_token(53);
        jj_consume_token(54);
        arrDepth++;
      }
      {if (true) return Expr.newArr(this, type, arrSize, arrDepth);}
      break;
    case 55:
      jj_consume_token(55);
      List < Expr > argList = new ArrayList < Expr > ();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOT:
      case MINUS:
      case MULDIV:
      case NULL:
      case NEW:
      case ID:
      case NUMBER:
      case 55:
        argList = argList();
        break;
      default:
        jj_la1[38] = jj_gen;
        ;
      }
      jj_consume_token(56);
      {if (true) return Expr.newObj(this, type, argList);}
      break;
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String id() throws ParseException {
  Token t;
    t = jj_consume_token(ID);
    {if (true) return win2utf(t.image);}
    throw new Error("Missing return statement in function");
  }

  final public short number() throws ParseException {
  Token t;
    t = jj_consume_token(NUMBER);
    {if (true) return Short.parseShort(t.image);}
    throw new Error("Missing return statement in function");
  }

  final public List < Expr > argList() throws ParseException {
  List < Expr > res = new ArrayList < Expr > ();
  Expr arg;
    arg = expr();
    res.add(arg);
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 57:
        ;
        break;
      default:
        jj_la1[40] = jj_gen;
        break label_12;
      }
      jj_consume_token(57);
      arg = expr();
      res.add(arg);
    }
    {if (true) return res;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(TRAP)) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_34()) return true;
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_33()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_scan_token(58)) return true;
    return false;
  }

  private boolean jj_3R_50() {
    if (jj_3R_52()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_49() {
    if (jj_scan_token(53)) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_3R_26()) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(53)) return true;
    if (jj_scan_token(54)) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_scan_token(59)) return true;
    return false;
  }

  private boolean jj_3R_41() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) return true;
    }
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_30()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_31()) jj_scanpos = xsp;
    if (jj_scan_token(51)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_16()) return true;
    if (jj_scan_token(58)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_3R_47()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_3R_46()) return true;
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_scan_token(NEW)) return true;
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(50)) return true;
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_scan_token(THROW)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) jj_scanpos = xsp;
    if (jj_scan_token(51)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) return true;
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_41()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(49)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) jj_scanpos = xsp;
    if (jj_scan_token(51)) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(PRINT)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_3R_30()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_scan_token(MULDIV)) return true;
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_3R_60()) return true;
    return false;
  }

  private boolean jj_3R_57() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) return true;
    }
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(WHILE)) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_scan_token(55)) return true;
    return false;
  }

  private boolean jj_3R_56() {
    if (jj_3R_57()) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_3R_66()) return true;
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_3R_65()) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_scan_token(IF)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  private boolean jj_3R_60() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_3R_45()) return true;
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(TRY)) return true;
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(53)) return true;
    if (jj_scan_token(54)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(55)) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_3R_53()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_3R_36()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_37()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_3R_13()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_51()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_35()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public EG1TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x81600001,0x81600000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80000000,0x0,0x600000,0xa000000,0x2000000,0x40028000,0x40028000,0x0,0x8000000,0x0,0x100,0x80,0x7e00,0x7e00,0x30000,0x30000,0xc0000,0xc0000,0x40028000,0x40000000,0x0,0x0,0x0,0x40028000,0x0,0x40000000,0x40028000,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x2087,0x2087,0x4880000,0x20000,0x2006,0x880000,0xc0000,0x200000,0x2006,0x2006,0xc0000,0x2000000,0x1,0x4000000,0x0,0x43a5e,0x41810,0x80a300,0x80a300,0x4000000,0x48,0x2200,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x80a300,0x80a300,0x2200,0x8200000,0x8200000,0x80a300,0x800000,0x808100,0x80a300,0xa00000,0x2000000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[5];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public EG1(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public EG1(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new EG1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public EG1(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new EG1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public EG1(EG1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(EG1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[60];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 60; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
